const express = require('express');
const router = express.Router();

// API Status endpoint
router.get('/status', (req, res) => {
  res.json({
    status: 'active',
    timestamp: new Date().toISOString(),
    service: 'generic_webapp',
    version: '1.0.0',
    features: ["User Authentication","CRUD Operations","Responsive Design"]
  });
});

// Sample data endpoint
router.get('/data', async (req, res) => {
  try {
    // This would typically fetch from database
    res.json({
      success: true,
      items: [
        {
          id: 1,
          title: 'Sample Item 1',
          description: 'This is a sample item generated by DevOps AI Agent',
          createdAt: new Date().toISOString()
        },
        {
          id: 2,
          title: 'Sample Item 2', 
          description: 'Another sample item with different content',
          createdAt: new Date().toISOString()
        }
      ]
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Generic submit endpoint
router.post('/submit', async (req, res) => {
  try {
    console.log('Received data:', req.body);
    
    // Process the submitted data here
    // This would typically save to database
    
    res.json({
      success: true,
      message: 'Data submitted successfully',
      data: req.body
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});





module.exports = router;